// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.giulius.tests {
    exports com.mastfrog.giulius.tests;

    // derived from com.google.inject/guice-0.0.0-? in com/google/inject/guice/5.1.0/guice-5.1.0.pom
    requires com.google.guice;

    // Inferred from source scan
    requires com.mastfrog.collections;

    // Sibling com.mastfrog/giulius-3.0.0-dev
    // Transitive detected by source scan
    requires com.mastfrog.giulius;
    requires com.mastfrog.giulius.settings;

    // Sibling com.mastfrog/giulius-annotations-3.0.0-dev
    requires com.mastfrog.giulius.annotations;

    // Inferred from source scan
    requires com.mastfrog.streams;

    // Inferred from source scan
    requires com.mastfrog.strings;

    // Inferred from source scan
    requires com.mastfrog.util.function;
    requires java.logging;

    // Inferred from test-source-scan
    // derived from junit/junit-4.13.2 in junit/junit/4.13.2/junit-4.13.2.pom
    requires junit;

}
