open module com.mastfrog.giulius.tests {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.giulius.tests;

    // derived from com.google.inject/guice-5.1.0 in com/google/inject/guice/5.1.0/guice-5.1.0.pom
    requires com.google.guice;
    requires com.mastfrog.giulius;
    requires com.mastfrog.giulius.annotations;
    requires com.mastfrog.giulius.settings;
    requires com.mastfrog.util.collections;
    requires com.mastfrog.util.function;
    requires java.logging;

    // derived from junit/junit-4.13.2 in junit/junit/4.13.2/junit-4.13.2.pom
    requires junit;
}
